export const typeClassMap: Record<string, string> = {
  normal: "bg-[#AAA67F] text-white",
  fire: "bg-[#F57D31] text-white",
  water: "bg-[#6493EB] text-white",
  electric: "bg-[#F9CF30] text-black",
  grass: "bg-[#74CB48] text-black",
  ice: "bg-[#9AD6DF] text-black",
  fighting: "bg-[#C12239] text-white",
  poison: "bg-[#A43E9E] text-white",
  ground: "bg-[#DEC16B] text-black",
  flying: "bg-[#A891EC] text-black",
  psychic: "bg-[#FB5584] text-white",
  bug: "bg-[#A7B723] text-black",
  rock: "bg-[#B69E31] text-black",
  ghost: "bg-[#70559B] text-white",
  dragon: "bg-[#7037FF] text-white",
  dark: "bg-[#75574C] text-white",
  steel: "bg-[#B7B9D0] text-black",
  fairy: "bg-[#E69EAC] text-black",
};
